### ISSUE TITLE
Implement FX Chain - EQ

### ISSUE THREAD

**Issue by jocekav** [jocekav/MUSI6106-Project#25]
Create a 5 band parametric EQ (highpass pass, low-mid, mid, high-mid notches and a low-pass)

Also create a 7 band graphic EQ (only controls for gain, using fixed Q and centres [50,125,320,750,2.2k,6k,16k])

**Comment by VedantKalbag** [comment]
https://docs.juce.com/master/tutorial_audio_processor_graph.html

Here's a link for reference for how to tie this into an AudioProcessorGraph
